### PR TITLE
added function query_execution_by_name

### PR DESCRIPTION
**Pull request by pdunk**
I added a function that allows to specify a name of a saved query and it will go through all executed queries, starting most recent first and pick the first query it finds with this specific SQL string and return the execution_id.

### CODE REVIEW

**Comment by pdunk** [comment]
Had to add the 2nd commit. I had missed the workgroup parameter in the NamedQueries request,

**Comment by mtanda** [comment]
Sorry, I didn't notice your contribution. (The feature seems very nice!)
And I just released newer version, it conflict your change.
If you don't mind, I'll merge your change to latest version.
If not, will you create new pull request?

**Comment by pdunk** [comment]
Hi,
thanks for reaching out to me.
I am not super experienced yet with pull requests, but I try to figure it
out to make another one.

Btw, I have spent some more time on the plugin, and I am working on adding
caching, so the same QueryExecutionID is not causing another query to AWS.
This works already well.

I also looked at the getResult part, and it was only loading some data not
all data of a query, I modified this now to getResultData with pages, so
all data is loaded, which can take a bit longer, but all data is provided.

As last step, I am trying to look closer into your dedupe logic, and I
think there are some cases where something gets lost, e.g. if you have 2
queries in 1 chat in Grafana, I think the 2nd query does not get data.

Should I rather make a separate branch for these other work items?

--
Peter

Peter Dunker
Senior Director Architecture

Gracenote a Nielsen Company

*Mobile:* +1 (510) 999-1836

https://www.gracenote.com/

**Comment by mtanda** [comment]
Cache is good idea.
Recently, I notice that Google Sheets datasource cache the result.
https://github.com/grafana/google-sheets-datasource

I do same thing in this PR.
https://github.com/mtanda/grafana-aws-athena-datasource/pull/18

I still consider where cache duration setting should I hold.

**Comment by mtanda** [comment]
> Should I rather make a separate branch for these other work items?

I'm not sure how do you open PR. Because GitHub show the source repository is 'unknown repository'.
Anyway, I don't mind branch.

**Comment by pdunk** [comment]
Hi, I will do a new PR, I actually deleted my repo and re-created it, just
got lost in all the merging, and will do the code changes again.

With all the changes I still need to figure out building and packaging for
my testing again and I  may need some more time.

Re-Cache, I added this cache:
"github.com/patrickmn/go-cache"

Re cache-time, I would cache the result of the QueryResult query, before
any manipulations, and since the result for a specific Queryexecution is
always the same and will never change, I was thinking cache-time can be a
day or even longer. I guess the only concern is potential high mem usage of
the plugin/grafana.

I also added a functionality that it case you have multiple charts with the
same queryID, which will cause multiple parallel executed queries to the
plugin, make sure only the first is querying Athena and the others wait for
the result being cached. This worked nicely, just need to re-do it all ;-)

**Comment by mtanda** [comment]
Thanks for explanation about cache strategy!
Now, I understand why using query execution id as cache key.

> Re-Cache, I added this cache:
> "github.com/patrickmn/go-cache"

I already use same cache library.

To avoid conflict with your PR, I'll merge my PR soon.

**Comment by mtanda** [comment]
About memory usage, new Grafana plugin sdk provide metrics export feature for Prometheus.
https://grafana.com/docs/grafana/latest/developers/plugins/backend/#collect-metrics

If you use Prometheus, you can monitor memory usage.
```
❯ curl -s http://admin:admin@localhost:3000/api/plugins/mtanda-aws-athena-datasource/metrics | grep process_resident_memory_bytes
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 2.4395776e+07
```

**Comment by pdunk** [comment]
This is an old pull request, to avoid lots of merging, there are 2 smaller new separate pull requests.

**Pull request closed without merging**
